apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plant-sec-app-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MichaelFarook/plant2.git
    targetRevision: HEAD
    path: helm 
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: plant-sec
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
