{{- if eq .Values.global.environment "production" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: back-app-{{ .Values.global.environment }}
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MichaelFarook/backend.git
    targetRevision: {{ .Values.applications.backend_branch }}
    path: helm/backend
    helm:
      valueFiles:
      - $values/environments/{{ .Values.global.environment }}/environment-values/backend.yaml
      parameters:
      - name: "environment"
        value: {{ .Values.global.environment }}
      - name: "aws_account"
        value: {{ .Values.global.aws_account }}
      - name: "region"
        value: {{ .Values.global.region }}
      - name: "image.tag"
        value: {{ .Values.applications.backend_version }}
  destination:
    server: https://kubernetes.default.svc 
    namespace: {{ .Values.global.environment }} 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
