{{- range $app := .Values.argocdApplications -}}
{{ if not .disable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ $.Values.global.environment }}
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.global.spec.project }} 
  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }} 
    targetRevision: {{ .Values.applications.frontend_branch }}
    path: helm/{{ .name }}
    helm:
    {{- if default $.Values.global.helmDefault .helm }}
      valueFiles:
      - $values/environments/{{ .Values.global.environment }}/environment-values/frontend.yaml
    {{- end }}
      parameters:
      - name: "environment"
        value: {{ .Values.global.environment }}
      - name: "aws_account"
        value: {{ .Values.global.aws_account }}
      - name: "region"
        value: {{ .Values.global.region }}
      - name: "image.tag"
        value: {{ .Values.applications.frontend_version }}
  destination:
    server: https://kubernetes.default.svc 
    namespace: {{ .Values.global.environment }} 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---
{{- end }}
{{- end }}
