{{- if eq .Values.global.environment "production" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
  namespace: {{ .Values.global.environment }}
spec:
  provider:
    aws:
      region: {{ .Values.global.region }}
      service: SecretsManager
{{- end }}
