global:
  environment: production
  region: us-east-1
  aws_account: '123456789123'
applications:
  frontend_version: 0a421ad0dd55864a23cd8f9b935fb58edc350c44
  frontend_branch: null
  backend_version: null
  backend_branch: null
  bot_version: null
  bot_branch: null
