global:
  environment: production
  region: us-east-1
  aws_account: '123456789123'
applications:
  frontend_version: prod-ec77b1315ebbb33fb3a154e3718707c5250b9849
  backend_version: null
  bot_version: null
